### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by ZakariaSaad** [LunaPixelStudios/Better-Minecraft#20] opened 2022-01-11 02:36 UTC
### Describe the Bug

As I'm playing and doing normal Minecraft stuff, I randomly lose connection. this is on a server. 

### Reproduction Steps

1.make a server
2.join
3.play around I'm not sure what exactly is causing me to lose connection. 
...

### Screenshots and Videos

none

### Crash Report or Log

internal exception: java.lang.stackoverflowerror

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.1 v11

### Optifine

I used Optifine

### Other Mods

1.18.1 optifine

**Comment by switchnlade** [comment] 2022-01-11 03:11
Hello there, to better assist we need some logs, can you please upload the latest.log to pastebin or a similar site and give us the link?

**Comment by Sotxri** [comment] 2022-01-11 16:55
> 
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7848479/latest.log)
Not OP but I have the same Issue. We played for around 30min without any problems. Then the server crashed.

Now when re-starting the server, after a minute or so the server crashes again with the same error of StackOverflow. 

Logs say this `Caused by: java.lang.NoSuchFieldError: DIRT
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2343!:1.15.1]
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?]
	... 5 more`

It happend right as I was jumping in overworld on Grass/Dirtblocks. Might be a hint to what the error might be

With best regards :)

**Comment by switchnlade** [comment] 2022-01-11 17:35
> Logs say this `Caused by: java.lang.NoSuchFieldError: DIRT at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2343!:1.15.1] at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23171!:?] ... 5 more`

This is an error caused by forge 39.0.18 removing the tag forge:dirt, Alex's mobs hasn't updated to correct their mod for that change, the fix for this is using forge 39.0.17 or below.

**Comment by ArthasLightmoon** [comment] 2022-01-11 20:30
> This is an error caused by forge 39.0.18 removing the tag forge:dirt, Alex's mobs hasn't updated to correct their mod for that change, the fix for this is using forge 39.0.17 or below.


Hello there, having the same error that Sotrix said, my question is, how do you downgrade your server, or what do you need to modify on the server, so it can ensure to run the correct version 39.0.17?

Thank you

**Comment by switchnlade** [comment] 2022-01-11 20:44
A universal way would be backing up the world folder, and any changes done to the mods/configs/etc, then re-setup the server on 39.0.17, and moving your backups back in after it's been setup on the older forge version. Some server providers may have a system in place to swap forge versions without the need to save anything and do some tedious moving files, but I don't use any providers so I can't speak for them. For self hosting, I'd just setup a forge 39.0.17 server in a new folder, then move over your world folder, mods and configs folders, etc to that new forge server.

**Comment by SharkieTV** [comment] 2022-01-12 07:44
v12 came out fixing the issues.

**Closed by SharkieTV** 2022-01-12 07:44 UTC
Labels: bug, forge, Optifine, 1.18
