### ISSUE TITLE
Nether Basic Biomes aren´t Spawning

### ISSUE THREAD

**Issue by 0TheCho0** [LunaPixelStudios/Better-Minecraft#67] opened 2022-01-27 16:22 UTC
When you enter a world and the nether for first time you can generate the basic biomes of the nether like basalt deltas, crimson forest... but when you relog the biomes doesn´t generates and this is a problem because you have achivements related to them, like the hot tourist, but most important the structures like Awful Dungeon and The Tower from Cataclysm aren´t generating and you have some FTB quest that need them.

**Comment by SharkieTV** [comment] 2022-01-28 03:25
Duplicate of #57

**Closed by SharkieTV** 2022-01-28 03:25 UTC
