### ISSUE TITLE
My create mod texture is missing

### ISSUE THREAD

**Issue by JemPePaine** [LunaPixelStudios/Better-Minecraft#275] opened 2022-04-14 23:33 UTC
### Describe the Bug

i tried to put some mod item (shaft) and i doesent saw his texture

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![unknown](https://user-images.githubusercontent.com/103700445/163493035-07be48bc-d7f0-45dd-87ef-9531af766048.png)

### Operating System

windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

1.18.2 v5

### Optifine

No

### Other Mods

![Screenshot (31)](https://user-images.githubusercontent.com/103700445/163493328-7d12d50a-d04f-4504-b693-3415acf87aa0.png)
![Screenshot (27)](https://user-images.githubusercontent.com/103700445/163493331-04c97dd6-1c28-48db-a830-60d28929071d.png)
![Screenshot (28)](https://user-images.githubusercontent.com/103700445/163493332-e558934c-e04d-4744-8544-09893da25a6d.png)
![Screenshot (29)](https://user-images.githubusercontent.com/103700445/163493333-ed8c247d-5331-4cbd-8f41-21e1cdae9581.png)
![Screenshot (30)](https://user-images.githubusercontent.com/103700445/163493335-d8119cb9-611b-43f8-a210-aadca57e4d28.png)

**Comment by SharkieTV** [comment] 2022-04-15 00:52
Duplicate of #263

**Closed by SharkieTV** 2022-04-15 00:52 UTC
Labels: bug, forge, 1.18
