### ISSUE TITLE
World crash when creating new world

### ISSUE THREAD

**Issue by FruitMaestro** [LunaPixelStudios/Better-Minecraft#99] opened 2022-02-07 20:49 UTC
### Describe the Bug

When I try to create a new world or load the saved one, the loading show 100% and then crashes.

### Reproduction Steps

1. Open Minecraft
2. Click "Create New World"
3. Crash

### Crash Report or Log

https://pastebin.com/Tvsjpy8d

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v41.5

### Optifine

I used Optifine

**Comment by switchnlade** [comment] 2022-02-07 21:06
Can you please upload the latest.log? That crash report is not related to a world loading crash, that's just a mod loading error that happens sometimes.

**Comment by FruitMaestro** [comment] 2022-02-07 22:17
[https://gist.github.com/FruitMaestro/8c980f33123fc23317cbd5194edbf7e3](url)

**Comment by switchnlade** [comment] 2022-02-07 22:18
That does not contain information about a crash, please attach the file so I can download it instead.

**Comment by FruitMaestro** [comment] 2022-02-07 22:20
[this one?](https://gist.github.com/FruitMaestro/8c980f33123fc23317cbd5194edbf7e3)

**Comment by switchnlade** [comment] 2022-02-07 22:23
Yes, that paste does not contain information about a crash, it's simply info about the loading. Use the attach feature below the text box and select your latest.log file manually. It should upload it to allow me to download it and view the entire file. 
Example of what I mean using the attach feature and a text document: 
[ExampleDownload.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8019151/ExampleDownload.txt)

**Comment by FruitMaestro** [comment] 2022-02-07 22:38
[latest.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8019236/latest.txt)

**Comment by switchnlade** [comment] 2022-02-08 00:44
Same issue as #83, can you try their fix. I do see you are on v41.5 though, which is quite out of date. Worst case, try on the latest version, which keep in mind will require a new world due to mod updates done in v52. If you don't want to restart, you can try updating one version at a time and see if it fixes it.

**Comment by switchnlade** [comment] 2022-02-08 00:46
Same issue as #83, I do see fpsreducer in your crash log, try without that mod first please. Ignore my previous comment, I missed where it mentioned that mod.

**Comment by SharkieTV** [comment] 2022-02-08 04:46
You are also on a very outdated version please update to latest

**Comment by FruitMaestro** [comment] 2022-02-08 19:32
Removing fpsreducer did not help: [fpsreducer off.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8026859/fpsreducer.off.txt)
Adding Not Enough Crashes mod did not help: ![Not Enough Crashes](https://user-images.githubusercontent.com/99217121/153061358-ee7c03f3-05f2-4b87-813c-949e1e18adb4.jpg)
Updating to newest version did not help: [New v54.5.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8026871/New.v54.5.txt)
The game still crashes after loading show 100%.

**Comment by switchnlade** [comment] 2022-02-08 22:51
My suggestion now is try Curseforge or GDLauncher.

**Comment by switchnlade** [comment] 2022-02-08 22:53
This is the cause most likely, though I'm only taking a guess since there's not much on the issue online/
![image](https://user-images.githubusercontent.com/96159041/153089270-d105c5d5-13e5-40f9-a242-960229b0a84d.png)

**Comment by FruitMaestro** [comment] 2022-02-08 23:16
> My suggestion now is try Curseforge or GDLauncher.

I am currently using MultiMC to play the two-player local game on one PC with NucleusCoop. As far as I know, the NucleusCoop does not work with Curseforge or GDLauncher. It may resolve the issue, but it won't help me. 

> This is the cause most likely, though I'm only taking a guess since there's not much on the issue online/
> 
> ```
> [20:17:03] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [20:17:04] [Render thread/ERROR] [minecraft/Minecraft]: Failed to verify authentication
> com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
> ```

If this is the issue then, am I even looking in the right place? Could it be caused by the modpack?
When I create the Minecraft 1.16.5 instance in MultiMC without the Better-Minecraft, I can play without the crash.

Also, how do I reopen the issue? I thought I can only reopen it when I am the one who close it.

**Comment by switchnlade** [comment] 2022-02-08 23:41
There should've been a reopen button next to comment, but regardless that allows you to do what I did above my comment here (note I only reopened to show you what it should do). It may be something in the modpack but overall, think of that app as our warning for the Open to LAN feature, it's untested and will probably have issues. 

This is the last bit of advice I will give, and will be closing this after since it's not really something we test or build for. This is from their site, follow the one you need, if it fails to work after that then well, perhaps it just doesn't work with our modpack (which works when used properly as in on singleplayer or a server): 
(If you have multiple Minecraft accounts) Select the first instance and click Launch. Change account in the top-right corner, then repeat for the next instance.
(If you have one Minecraft account) Select the first instance and click Launch Offline. Set your username to anything. Repeat for the next instance.

**Closed by switchnlade** 2022-02-08 23:41 UTC
Labels: bug, forge, 1.16, Optifine
