### ISSUE TITLE
Crash during chunk generation

### ISSUE THREAD

**Issue by Gr8umbreon** [LunaPixelStudios/Better-Minecraft#250] opened 2022-04-05 21:30 UTC
### Describe the Bug

Crash/Error issue when the world generates a biome chunk with specific tag; byg:firecracker_shrubland

### Reproduction Steps

If you're referring to Minecraft footsteps, there is a bit. Otherwise nothing other than when the world attempts to generate a chunk with specified biome. No additional mods. 2 additional datapacks which only affect Minecraft item drops and recipes. (They're listed as incompatible due to files not tied to a mod.) World with biome issue included, north direction of spawn location.
[World 14.zip](https://github.com/LunaPixelStudios/Better-Minecraft/files/8421972/World.14.zip)
 

### Crash Report or Log

https://pastebin.com/hWzFs4nf

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Fabric

### Modpack Version

Bmc[Fabric] 1.18.2 v4

### Optifine

No

**Comment by SharkieTV** [comment] 2022-04-06 00:17
Can you try without your datapacks on a new world?

**Comment by ArgalloK** [comment] 2022-04-06 05:42
I may have a similar problem. Perhaps some biome is buggy and when you enter it, the internal server crashes. Blocks are affected, but they do not fall out when destroyed, mobs do not spawn, and the world seems to freeze. Also, if you exit the game, there will be an infinite save. 
[https://youtu.be/UEuLnki7HFI](url)

**Comment by SharkieTV** [comment] 2022-04-06 07:21
The video wont help much as I know the issue, is this a new world on v4 or did you update?

> I may have a similar problem. Perhaps some biome is buggy and when you enter it, the internal server crashes. Blocks are affected, but they do not fall out when destroyed, mobs do not spawn, and the world seems to freeze. Also, if you exit the game, there will be an infinite save. Clean build without additional mods and datapacks. https://youtu.be/UEuLnki7HFI

**Comment by ArgalloK** [comment] 2022-04-06 07:30
> The video wont help much as I know the issue, is this a new world on v4 or did you update?

It's a new world on v3

**Comment by SharkieTV** [comment] 2022-04-06 07:38
> > The video wont help much as I know the issue, is this a new world on v4 or did you update?
> 
> It's a new world on v3

So im thinking you had the issue that is fixed in v4 that was caused by Unstructured mod, see if updating to v4 and a new world works

**Comment by SharkieTV** [comment] 2022-04-08 07:22
Will be fixed in new version

**Closed by SharkieTV** 2022-04-08 07:22 UTC
Labels: bug, fabric, 1.18
