### ISSUE TITLE
Crash Placing Simple Storage Root Block

### ISSUE THREAD

**Issue by rithirin** [LunaPixelStudios/Better-Minecraft#54] opened 2022-01-23 22:39 UTC
### Describe the Bug

When placing simple storage root block game crash's.

### Reproduction Steps

Just place the block.

### Crash Report or Log

https://pastebin.com/3Nu73fAL

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Better Minecraft [Forge] v14

### Optifine

No

**Comment by switchnlade** [comment] 2022-01-23 22:50
Known, remove simple storage network if it's recurring.
Duplicate of #53.

**Closed by switchnlade** 2022-01-23 22:50 UTC
Labels: bug, forge, 1.18
